spring:
  datasource:
    url: jdbc:mysql://localhost:3307/Spring2_travel360
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

managment:
  endpoint:
    web:
      exposure:
        include: info,health

# ACTUATOR INFO
info:
  app:
    name: @projecct.name@
    version: @project.version@
    profile: ${spring.profiles.active}
  serverInfo:
    os: ${os.name}