spring:
  datasource:
    url: jdbc:mysql://localhost:3307/Spring2_travel360
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update


  mail:
    host: smtp.gmail.com
    port: 587
    username: sda.pawel.rzeszow@gmail.com
    password: supergigahaslo9
    default-encoding: UTF-8
    protocol: smtp
    properties:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
      mail.smtp.starttls.enable: true
      mail.smtp.auth: true


# ACTUATOR INFO
info:
  app:
    name: @project.name@
    version: @project.version@
    profile: ${spring.profiles.active:}
  serverInfo:
    os: ${os.name}
    osVersion: ${os.version}
  user:
    timeZone: ${user.timezone}
    country: ${user.country}

management:
  endpoints:
    web:
      exposure:
        include: '*'
